version: '3.1'

services:
  search-api-db:
    image: "postgres:13.4"
    container_name: search-api-db
    restart: always
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_password
      POSTGRES_DB: fastapi_db
    ports:
      - 5432:5432
